{% set version = "0.6.5" %}

package:
  name: arro3-core-modules
  version: {{ version }}

source:
  url: https://github.com/kylebarron/arro3/archive/refs/tags/py-v{{ version }}.tar.gz
  sha256: cdb9b0a6b17834310b197d064b0eafef27191dda0b342fca289b96325f0a354b

build:
  # Build issue https://github.com/conda-forge/arro3-core-feedstock/pull/32
  skip: true  # [py==3.14 and (aarch64 or ppc64le)]
  number: 0

outputs:
  - name: arro3-core
    script: build-pkg.sh  # [not win]
    script: build-pkg.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - maturin >=1.7.0,<2.0                   # [build_platform != target_platform]
        - {{ stdlib("c") }}
        - {{ compiler("c") }}
        - {{ compiler("rust") }}
        - cargo-bundle-licenses
      host:
        - python
        - maturin >=1.4.0,<2.0
        - pip
      run:
        - python
        - typing_extensions >=4.6.0  # [py<312]
    test:
      imports:
        - arro3.core
      commands:
        - pip check
      requires:
        - pip

  - name: arro3-compute
    script: build-pkg.sh  # [not win]
    script: build-pkg.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - maturin >=1.7.0,<2.0                   # [build_platform != target_platform]
        - {{ stdlib("c") }}
        - {{ compiler("c") }}
        - {{ compiler("rust") }}
        - cargo-bundle-licenses
      host:
        - python
        - maturin >=1.4.0,<2.0
        - pip
      run:
        - python
        - {{ pin_subpackage("arro3-core", exact=True) }}
        - typing_extensions >=4.6.0  # [py<312]
    test:
      imports:
        - arro3.compute
      commands:
        - pip check
      requires:
        - pip

  - name: arro3-io
    script: build-pkg.sh  # [not win]
    script: build-pkg.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - maturin >=1.7.0,<2.0                   # [build_platform != target_platform]
        - {{ stdlib("c") }}
        - {{ compiler("c") }}
        - {{ compiler("rust") }}
        - cargo-bundle-licenses
      host:
        - python
        - maturin >=1.4.0,<2.0
        - pip
      run:
        - python
        - {{ pin_subpackage("arro3-core", exact=True) }}
        - typing_extensions >=4.6.0  # [py<312]
    test:
      imports:
        - arro3.io
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/kylebarron/arro3
  summary: Core library for representing Arrow data in Python.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE_MIT
    - THIRDPARTY.yml
  license_url: https://github.com/kylebarron/arro3/blob/main/LICENSE_MIT
  doc_url: https://kylebarron.dev/arro3
  dev_url: https://github.com/kylebarron/arro3

extra:
  recipe-maintainers:
    - kylebarron
  feedstock-name: arro3-core
