{% set version = "0.4.2" %}

package:
  name: arro3-core
  version: {{ version }}

source:
  url: https://github.com/kylebarron/arro3/archive/refs/tags/py-v{{ version }}.tar.gz
  sha256: f2f929b1f69d2837b39aafc443611f7bb0e51f8e3f7aa1f1537d855602c5af1f

build:
  script:
    - {{ PYTHON }} -m pip install ./arro3-core -vv
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.7.0,<2.0                   # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.4.0,<2.0
    - pip
  run:
    - python

test:
  imports:
    - arro3.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kylebarron/arro3
  summary: Core library for representing Arrow data in Python.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE_MIT
    - THIRDPARTY.yml
  license_url: https://github.com/kylebarron/arro3/blob/main/LICENSE_MIT
  doc_url: https://kylebarron.dev/arro3
  dev_url: https://github.com/kylebarron/arro3

extra:
  recipe-maintainers:
    - kylebarron
